import React,{useState} from 'react';
import {Upload, Wand2, Scissors, Shirt, Sparkles, Square, Save, ShoppingBag, Loader2, CheckCircle2, AlertCircle, ArrowLeft} from 'lucide-react';
const API=import.meta.env.VITE_AI_API||'http://localhost:8000';
const stages=[['upload','Upload',Upload],['remove_bg','Remove BG',Scissors],['detect','Detect',Shirt],['generate','Compose',Wand2],['enhance','Enhance',Sparkles],['save','Save',Save],['add','Catalog',ShoppingBag]];
export default function AssetStudio({onAddProduct}){
 const [file,setFile]=useState(),[preview,setPreview]=useState(''),[mode,setMode]=useState('hanging'),[stage,setStage]=useState('upload'),[result,setResult]=useState(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('Ready'),[product,setProduct]=useState({name:'',price:'',category:'Men',style:'Casual'});
 const idx=Math.max(0,stages.findIndex(x=>x[0]===stage));
 function choose(e){const f=e.target.files?.[0];if(!f)return;setFile(f);setPreview(URL.createObjectURL(f));setResult();setError('');setStage('upload');setStatus('Photo ready');}
 async function process(){if(!file)return;setBusy(true);setError('');setResult();try{const fd=new FormData();fd.append('file',file);fd.append('mode',mode);setStage('remove_bg');setStatus('Removing background…');const r=await fetch(`${API}/api/product-studio/process`,{method:'POST',body:fd});if(!r.ok){const t=await r.text();throw new Error(t||`HTTP ${r.status}`)}setStage('detect');setStatus('Detecting garment…');const data=await r.json();setStage('generate');setStatus(mode==='hanging'?'Building hanging catalog composition…':'Building flat-lay catalog composition…');setStage('enhance');setStatus('Enhancing image…');setStage('save');setStatus('Saved locally');setResult(data);setStage('add');setStatus('Ready to add to catalog');}catch(e){setError(`Product Studio could not process the image. Make sure the AI service is running at ${API}. ${e.message}`);setStatus('Processing failed');setStage('upload')}finally{setBusy(false)}}
 function add(){if(!result||!product.name||!product.price){setError('Enter product name and price before adding.');return}onAddProduct?.({...product,image_url:`${API}${result.output_url}`,generated_mode:mode});}
 return <section className="studio"><div className="studioHead"><div><button className="back" onClick={()=>history.back()}><ArrowLeft size={16}/> Back</button><span className="eyebrow">MERCHANT TOOL</span><h1>Product Studio</h1><p>Turn one raw garment photo into a clean Vastram catalog asset. No API key is required.</p></div><div className="localBadge"><span/> LOCAL PROCESSOR</div></div><div className="studioFlow">{stages.map(([id,label,Icon],i)=><div className={`studioStage ${i<=idx?'done':''} ${stage===id?'current':''}`} key={id}><div><Icon/></div><small>{label}</small></div>)}</div><div className="studioGrid"><div className="studioCard"><div className="uploadBox">{preview?<img src={preview} alt="garment"/>:<><Upload size={40}/><b>Drop garment photo here</b><span>JPG, PNG or WEBP · one garment per photo</span></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choose}/></div><div className="modeRow"><button className={mode==='hanging'?'mode active':'mode'} onClick={()=>setMode('hanging')}><Wand2/> Hanging</button><button className={mode==='flatlay'?'mode active':'mode'} onClick={()=>setMode('flatlay')}><Square/> Flat-lay</button></div><button className="primary studioBtn" disabled={!file||busy} onClick={process}>{busy?<><Loader2 className="spin"/> Processing…</>:<><Sparkles/> Create catalog image</>}</button>{error&&<div className="studioError"><AlertCircle size={18}/>{error}</div>}</div><div className="studioCard resultCard"><div className="resultTop"><span className="eyebrow">OUTPUT</span><span>{status}</span></div><div className="resultPreview">{result?<img src={`${API}${result.output_url}`} alt="Vastram catalog output"/>:<div className="emptyStudio"><Shirt size={42}/><b>Catalog image appears here</b><small>Background removal → garment isolation → composition → enhancement</small></div>}</div>{result&&<div className="productForm"><label>Product name<input value={product.name} onChange={e=>setProduct({...product,name:e.target.value})} placeholder="e.g. Oxford Structured Shirt"/></label><div className="two"><label>Price<input inputMode="numeric" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})} placeholder="1299"/></label><label>Category<select value={product.category} onChange={e=>setProduct({...product,category:e.target.value})}><option>Men</option><option>Women</option><option>Kids</option><option>Ethnic</option><option>Western</option><option>Footwear</option><option>Accessories</option></select></label></div><button className="primary" onClick={add}><ShoppingBag size={17}/> Add to Vastram catalog</button></div>}</div></div><div className="studioNote"><CheckCircle2/><div><b>Commerce-safe fallback</b><span>The included local pipeline preserves the real garment instead of hallucinating new product details. The production AI generation layer can be connected separately through a hosted ZeroGPU Space.</span></div></div></section>
}
